<?php

namespace Mada\Bundle\CarAppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RouteToUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteToUserRepository extends EntityRepository
{
}
